### ISSUE TITLE
checkin和state '{"code":-2,"message":"没有权限"}'

### ISSUE THREAD

**Issue by wajika** [hbstarjason/glados-checkin#2]
配置
![image](https://user-images.githubusercontent.com/17058349/103610857-05edfb00-4f5c-11eb-9cfc-c5b653bd4924.png)

 checkin = requests.post(url,headers={'cookie': cookie ,'referer': referer,'origin':origin,'user-agent':useragent,'content-type':'application/json;charset=UTF-8'},data=json.dumps(payload))
    state =  requests.get(url2,headers={'cookie': cookie ,'referer': referer,'origin':origin,'user-agent':useragent})

checkin和state 没有成功拿到数据   提示 '{"code":-2,"message":"没有权限"}'

**Comment by LengSword** [comment]
应该是Cookie不全的问题

**Comment by wajika** [comment]
好像用cookie的方法失效了
